import "~/styles/globals.css";
import { type Metadata } from "next";
import { Lexend } from "next/font/google";

import { SessionProvider } from "next-auth/react";
import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "~/components/shared/Navbar";
import { Toaster } from "~/components/ui/sonner";
import { ThemeProvider } from "~/components/theme-provider";
import { MotionLazyProvider } from "~/components/providers/MotionLazyProvider";
import Footer from "~/components/shared/Footer";

// === SEO Konfigurasi ===
const siteUrl = "https://darrellvalentino.com";

export const metadata: Metadata = {
  // === INFORMASI DASAR ===
  metadataBase: new URL(siteUrl),
  title: {
    default: "Darrell Valentino | Personal Website",
    template: "%s | Darrell Valentino",
  },
  description:
    "Portofolio Darrell Valentino, Full-Stack Web Developer berbasis di Jakarta, lulusan Sistem Informasi ITS. Lihat proyek React, Next.js, TypeScript saya.", // Deskripsi kaya keyword
  applicationName: "Darrell Valentino Portfolio",
  authors: [{ name: "Darrell Valentino", url: siteUrl }],
  creator: "Darrell Valentino",
  publisher: "Darrell Valentino",

  // === KEYWORDS (Penting untuk konteks) ===
  keywords: [
    "Darrell Valentino",
    "Darrell",
    "Valentino",
    "Portfolio",
    "Full-Stack Developer",
    "Web Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Jakarta",
    "Indonesia",
    "Sistem Informasi",
    "ITS",
    "Institut Teknologi Sepuluh Nopember",
    "HMSI",
    "Sistem Informasi ITS",
    "Pengembang Web",
    "Prisma",
    "tRPC",
    "Tailwind CSS",
  ],

  // === ROBOTS & INDEXING ===
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: siteUrl,
  },

  // === OPEN GRAPH (Untuk Facebook, LinkedIn, dll.) ===
  openGraph: {
    title: "Darrell Valentino - Full-Stack Developer Portfolio",
    description:
      "Lihat proyek dan pengalaman Darrell Valentino, seorang Full-Stack Web Developer dari Jakarta (Sistem Informasi ITS). Spesialisasi React, Next.js, TypeScript, Prisma, tRPC.",
    url: siteUrl,
    siteName: "Darrell Valentino Portfolio",
    images: [
      {
        url: `${siteUrl}/opengraph-image`, // Dynamic OG image generated by Next.js
        width: 1200,
        height: 630,
        alt: "Darrell Valentino - Full-Stack Web Developer Portfolio",
        type: "image/png",
      },
    ],
    locale: "id_ID",
    type: "profile",
    username: "darrellv14",
    emails: ["darrellspam14@gmail.com"],
  },

  // === TWITTER CARD (Untuk Twitter/X) ===
  twitter: {
    card: "summary_large_image",
    title: "Darrell Valentino - Full-Stack Developer Portfolio",
    description:
      "Portofolio Darrell Valentino, Full-Stack Web Developer di Jakarta. Spesialisasi React, Next.js, TypeScript, Prisma, tRPC.",
    site: "@nanangnursamsu",
    creator: "@nanangnursamsu",
    images: [`${siteUrl}/twitter-image`], // Dynamic Twitter image
  },

  // === VERIFICATION TAGS (Untuk Google Search Console, Bing, dll) ===
  verification: {
    // google: "your-google-verification-code", // Uncomment dan isi setelah daftar Google Search Console
    // yandex: "your-yandex-verification-code",
    // bing: "your-bing-verification-code",
  },

  // === IKON & MANIFEST ===
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    other: [
      { rel: "icon", url: "/favicon-16x16.png", sizes: "16x16" },
      { rel: "icon", url: "/favicon-32x32.png", sizes: "32x32" },
      { rel: "icon", url: "/android-chrome-192x192.png", sizes: "192x192" },
      { rel: "icon", url: "/android-chrome-512x512.png", sizes: "512x512" },
    ],
  },
  manifest: `${siteUrl}/site.webmanifest`,

  // === INFORMASI TAMBAHAN ===
  formatDetection: {
    telephone: false,
  },
};
// === Akhir SEO Konfigurasi ===

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-lexend",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // === JSON-LD Structured Data (Enhanced for Maximum SEO) ===
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      // Person Schema
      {
        "@type": "Person",
        "@id": `${siteUrl}/#person`,
        name: "Darrell Valentino",
        alternateName: ["Delvin", "Darrell", "Valentino"],
        givenName: "Darrell",
        familyName: "Valentino",
        url: siteUrl,
        image: {
          "@type": "ImageObject",
          url: `${siteUrl}/profile-image.webp`,
          width: 400,
          height: 400,
        },
        email: "darrellspam14@gmail.com",
        sameAs: [
          "https://github.com/darrellv14",
          "https://id.linkedin.com/in/darrellvalentino",
          "https://www.instagram.com/darrellwidjaja/",
        ],
        jobTitle: "Full-Stack Web Developer",
        description:
          "Full-Stack Web Developer spesialisasi React, Next.js, TypeScript, dan modern web technologies",
        worksFor: {
          "@type": "Organization",
          name: "PT Bank Central Asia (BCA) Tbk",
          url: "https://www.bca.co.id/",
        },
        alumniOf: {
          "@type": "CollegeOrUniversity",
          name: "Institut Teknologi Sepuluh Nopember",
          alternateName: "ITS",
          url: "https://www.its.ac.id/",
          department: {
            "@type": "Organization",
            name: "Sistem Informasi ITS",
          },
        },
        knowsAbout: [
          "Web Development",
          "Full-Stack Development",
          "React.js",
          "Next.js",
          "TypeScript",
          "JavaScript",
          "Node.js",
          "PostgreSQL",
          "Prisma ORM",
          "tRPC",
          "Tailwind CSS",
          "RESTful API",
          "Git",
          "Sistem Informasi",
          "Software Engineering",
          "UI/UX Design",
          "Responsive Design",
        ],
        knowsLanguage: ["Indonesian", "English"],
        address: {
          "@type": "PostalAddress",
          addressLocality: "Jakarta",
          addressRegion: "DKI Jakarta",
          addressCountry: "ID",
        },
      },
      // Website Schema
      {
        "@type": "WebSite",
        "@id": `${siteUrl}/#website`,
        url: siteUrl,
        name: "Darrell Valentino Portfolio",
        description:
          "Personal portfolio website of Darrell Valentino - Full-Stack Web Developer",
        publisher: {
          "@id": `${siteUrl}/#person`,
        },
        inLanguage: "id-ID",
        potentialAction: {
          "@type": "SearchAction",
          target: {
            "@type": "EntryPoint",
            urlTemplate: `${siteUrl}/?s={search_term_string}`,
          },
          "query-input": "required name=search_term_string",
        },
      },
      // ProfilePage Schema
      {
        "@type": "ProfilePage",
        "@id": `${siteUrl}/#profilepage`,
        url: siteUrl,
        name: "Darrell Valentino - Full-Stack Developer Portfolio",
        datePublished: "2024-01-01",
        dateModified: new Date().toISOString(),
        mainEntity: {
          "@id": `${siteUrl}/#person`,
        },
        breadcrumb: {
          "@type": "BreadcrumbList",
          itemListElement: [
            {
              "@type": "ListItem",
              position: 1,
              name: "Home",
              item: siteUrl,
            },
          ],
        },
      },
    ],
  };
  // === Akhir JSON-LD ===

  return (
    <html
      lang="en"
      className={`${lexend.variable} h-full !scroll-smooth`}
      suppressHydrationWarning
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="bg-background text-foreground flex min-h-screen flex-col antialiased">
        <SessionProvider>
          <TRPCReactProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <MotionLazyProvider>
                <Navbar />
                <div className="flex-1">
                  <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 2xl:max-w-[90rem]">
                    <main>{children}</main>
                  </div>
                </div>
                <Footer />
                <Toaster />
              </MotionLazyProvider>
            </ThemeProvider>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
